--- # 数据源配置
spring:
  # Azure配置
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources:
            - endpoint: ${ENDPOINT_URL}
              credential:
                client-secret: ${AZURE_CLIENT_SECRET}
                client-id: ${AZURE_CLIENT_ID}
              profile:
                cloud-type: ${AZURE_CLOUD_TYPE}
                tenant-id: ${AZURE_TENANT_ID}
              retry:
                mode: exponential
                exponential:
                  max-retries: 4
                  base-delay: PT0.0801S
                  max-delay: PT9S

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: true
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          url: ${ruoyi-ai-url-local} # MySQL Connector/J 8.X 连接的示例
          username: ${ruoyi-ai-username-local}
          password: ${ruoyi-ai-password-local}

  mail:
    username: HuiZhu

--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring.data:
  redis:
    # 地址
    host: ${ruoyi-ai-redis-url-local}
    # 端口，默认为6379
    port: ${ruoyi-ai-redis-port-local}
    # 数据库索引
    database: 0
    # 密码(如没有密码请注释掉)
    password: ${ruoyi-ai-redis-password-local}

--- # sms 短信
sms:
  enabled: false
  # 阿里云 dysmsapi.aliyuncs.com
  # 腾讯云 sms.tencentcloudapi.com
  endpoint: "dysmsapi.aliyuncs.com"
  accessKeyId: xxxxxxx
  accessKeySecret: xxxxxx
  signName: 测试
  # 腾讯专用
  sdkAppId:

pdf:
  extract:
    service:
      url: http://localhost:8080
    ai-api:
      url: https://api.pandarobot.chat/v1/chat/completions
      key: sk-xxxx
  transition:
    # 是否开启mineru
    enable-minerU: true
    # mineru conda环境路径
    conda-env-path: "F:\\ProgramData\\Computer\\Anaconda\\envs\\mineru"
    # 是否开启图片OCR
    enable-ocr: true






